runtime: java17
entrypoint: java -jar target/owlfinancebackend-1.0-SNAPSHOT.jar
service: owlfinancebackend
service_account: comp413@rice-comp-539-spring-2022.iam.gserviceaccount.com
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: rice-comp-539-spring-2022-423671897e9b.json